#spring:
#  application:
#    name: registry
#  cloud:
#    config:
#      uri: http://config:8888
#      fail-fast: true
#      password: ${CONFIG_SERVICE_PASSWORD:testpassword}
#      username: user

spring:
  application:
    name: registry

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0