#spring:
#  application:
#    name: registry
#  cloud:
#    config:
#      uri: http://config:8888
#      fail-fast: true
#      password: ${CONFIG_SERVICE_PASSWORD:testpassword}
#      username: user

spring:
  application:
    name: registry

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: false
    hostname: registry
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://registry1:8762/eureka/