security:
  oauth2:
    client:
      clientId: app
      clientSecret: testpassword
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      userInfoUri: http://localhost:5000/auth/user

spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://rm-uf6h5f480vusyxr9h.mysql.rds.aliyuncs.com:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: zhangpengcheng
      password: Zjtrust2017#
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 50
      minIdle: 50
      maxActive: 300
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      testWhileIdle: true
      test-on-borrow: true
      testOnBorrow: true
      validationQuery: SELECT 1

    db2:
      jdbc-url: jdbc:mysql://rm-uf6h5f480vusyxr9h.mysql.rds.aliyuncs.com:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: zhangpengcheng
      password: Zjtrust2017#
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 50
      minIdle: 50
      maxActive: 300
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      testWhileIdle: true
      test-on-borrow: true
      testOnBorrow: true
      validationQuery: SELECT 1

    redis:
      database: 0
      host: r-uf6d0558sqbkjbp0lf.redis.rds.aliyuncs.com
      password: Zjtrust2017#
      port: 6379
      timeout: 5000
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 500
        max-wait: 10000


server:
  servlet:
    context-path: /demo
  port: 8081
